spring:
  application:
    name: backend-spring
    formatted-version: (v1.0.0)
    description: A Simple Backend Demo
  datasource:
    url: jdbc:postgresql://postgres.cflbok8nvvfz.us-east-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Samsung10
  jpa:
    postgres:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
